# Generated by Django 5.2 on 2025-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_cover_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
