# Generated by Django 5.2 on 2025-05-14 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='controller_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
