# Generated by Django 5.2 on 2025-05-14 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_controller_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='controller_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
